google:
  spreadsheet:
    id: your_value
    mainList: your_value
  credentials:
    path: /credentials/google-sheet-credentials.json
  application:
    name: your_value
  calendar:
    id: your_value
telegram:
  name: your_value
  token: your_value
  ownerChat:
    id: your_value